const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn,execFile}=require('node:child_process');const {deliver}=require('../src/delivery.cjs');const pause=ms=>new Promise(r=>setTimeout(r,ms));
module.exports=async({win,nativeRequest,pasteText,folder,insertionTestTargets})=>{
 const {clipboard,ClipboardItem}=require('electron');const oldClipboard=await Promise.all((await clipboard.read()).map(async item=>new ClipboardItem(Object.fromEntries(await Promise.all(item.types.map(async type=>[type,await item.getType(type)]))))));
 const children=[];const make=async suffix=>{const output=path.join(folder,'delivery-'+Date.now()+'-'+suffix+'.txt');const child=spawn('powershell.exe',['-NoProfile','-STA','-File',path.join(__dirname,'paste-target.ps1'),'-OutputFile',output],{windowsHide:true,stdio:'ignore'});children.push(child);for(let i=0;i<150&&!fs.existsSync(output+'.ready');i++)await pause(100);assert.ok(fs.existsSync(output+'.ready'));const handle=fs.readFileSync(output+'.ready','utf8').trim();insertionTestTargets.add(handle);return {handle,pid:child.pid,app:'Disposable test field',output};};
 const focus=async target=>{fs.writeFileSync(target.output+'.focus','focus');for(let i=0;i<50;i++){const current=await nativeRequest('capture');if(current.handle===target.handle&&current.pid===target.pid)return;await pause(100);}throw new Error('Test field did not acquire focus. No text sent.');};
 let restores=0;const send=(destination,text)=>deliver({destination,ownPid:process.pid,capture:()=>nativeRequest('capture'),restore:d=>{restores++;return nativeRequest('restore-target',{handle:d.handle,pid:d.pid,babjiPid:process.pid});},paste:pasteText,copy:v=>clipboard.writeText(v),text});
 try{
  const target=await make('target');await focus(target);assert.equal((await send(target,'Direct insertion\nSecond line')).status,'inserted');assert.ok(fs.readFileSync(target.output,'utf8').replace(/\r/g,'').includes('Direct insertion\nSecond line'));
  win.show();win.focus();await new Promise((resolve,reject)=>execFile('powershell.exe',['-NoProfile','-File',path.join(__dirname,'focus-window.ps1'),'-WindowHandle',win.getNativeWindowHandle().readBigUInt64LE().toString(),'-ExpectedProcess',String(process.pid)],{windowsHide:true},e=>e?reject(e):resolve()));
  assert.equal((await nativeRequest('capture')).pid,process.pid,'Restoration test must begin with Babji focused');
  const restored=await send(target,' Restored insertion');assert.equal(restored.status,'inserted',JSON.stringify(restored));assert.ok(fs.readFileSync(target.output,'utf8').includes('Restored insertion'));
  const other=await make('unrelated');await focus(other);const before=fs.readFileSync(target.output,'utf8');const previousRestores=restores;const blocked=await send(target,'Must not reach unrelated field');assert.equal(blocked.status,'failed');assert.equal(blocked.copied,true);assert.ok(!(fs.existsSync(other.output)?fs.readFileSync(other.output,'utf8'):'').includes('Must not reach unrelated field'));assert.equal(fs.readFileSync(target.output,'utf8'),before);assert.equal(await clipboard.readText(),'Must not reach unrelated field');
  assert.equal(restores,previousRestores,'Do not steal focus from another app');
  fs.writeFileSync(path.join(folder,'delivery-results.json'),JSON.stringify({passed:true,directInsertion:true,returnsFromBabji:true,unrelatedWindowProtected:true,clipboardFallback:true}));console.log('DELIVERY PASSED: real Windows paste, return from Babji, unrelated-window protection, clipboard recovery.');
 }finally{for(const child of children)child.kill();await clipboard.write(oldClipboard);win.hide();insertionTestTargets.clear();}
};
